version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  # output will be in .\netDumbster\bin\release\netstandard2.0\ & .\netDumbster\bin\release\net451\ 
  - cmd: dotnet build -c release
after_build:
  # For once the build has completed
artifacts:
  # Nothing here right now
clone_depth: 1
test_script:
  # run the unit tests (requires changing into the test directory)
  # Nothing here right now
on_finish:
  # any cleanup in here
deploy: off